import { X, Sparkles, MessageSquare, Users, Zap } from 'lucide-react';

const STEPS = [
    {
        icon: <Sparkles size={22} className="text-[#00a884]" />,
        title: 'Summarise any chat',
        body: (
            <>
                <p>Select a chat from the sidebar, set how many messages to fetch, then hit <strong className="text-[#e9edef]">Summarise</strong>.</p>
                <p className="mt-2">Summaries are generated by Groq AI and sent to your ntfy topic if configured.</p>
            </>
        ),
    },
    {
        icon: <MessageSquare size={22} className="text-[#00a884]" />,
        title: '!summarise command',
        body: (
            <>
                <p>Type <code className="bg-[#0b141a] text-[#00a884] px-1.5 py-0.5 rounded text-sm">!summarise</code> or <code className="bg-[#0b141a] text-[#00a884] px-1.5 py-0.5 rounded text-sm">!summarize</code> in <strong className="text-[#e9edef]">any WhatsApp chat</strong> from your phone.</p>
                <p className="mt-2">The bot will summarise the last N messages and reply directly in the chat.</p>
                <p className="mt-2 text-xs">Tip: add a number — <code className="bg-[#0b141a] text-[#00a884] px-1.5 py-0.5 rounded">!summarise 100</code></p>
            </>
        ),
    },
    {
        icon: <Zap size={22} className="text-[#00a884]" />,
        title: '!general command',
        body: (
            <>
                <p>Ask the AI anything directly from WhatsApp:</p>
                <p className="mt-2"><code className="bg-[#0b141a] text-[#00a884] px-1.5 py-0.5 rounded text-sm">!general what is quantum computing</code></p>
                <p className="mt-2">The bot replies with the answer in the same chat. Works in any group or DM.</p>
                <p className="mt-2 text-xs">Tip: request a word count — <code className="bg-[#0b141a] text-[#00a884] px-1.5 py-0.5 rounded">!general explain X in 50 words</code></p>
            </>
        ),
    },
    {
        icon: <Users size={22} className="text-[#00a884]" />,
        title: 'Auto-summaries',
        body: (
            <>
                <p>Group chats are automatically summarised when unread messages cross a threshold.</p>
                <p className="mt-2">The summary is posted straight back into the group and sent to your ntfy topic.</p>
                <p className="mt-2 text-xs">You can adjust the threshold in the <strong className="text-[#e9edef]">.env</strong> file via <code className="bg-[#0b141a] text-[#00a884] px-1.5 py-0.5 rounded">AUTO_SUMMARY_THRESHOLD</code>.</p>
            </>
        ),
    },
];

export default function TutorialModal({ onClose }) {
    return (
        <div className="fixed inset-0 z-50 bg-black/70 flex items-center justify-center p-4">
            <div className="w-full max-w-lg bg-[#202c33] border border-[#2a3942] rounded-2xl shadow-2xl flex flex-col max-h-[90vh]">

                {/* Header */}
                <div className="flex items-center justify-between px-5 py-4 border-b border-[#2a3942]">
                    <h2 className="text-[#e9edef] font-semibold text-base">Quick start guide</h2>
                    <button
                        onClick={onClose}
                        className="text-[#8696a0] hover:text-[#e9edef] p-1 rounded-full hover:bg-[#2a3942]"
                    >
                        <X size={16} />
                    </button>
                </div>

                {/* Steps */}
                <div className="overflow-y-auto px-5 py-4 space-y-5">
                    {STEPS.map((step, i) => (
                        <div key={i} className="flex gap-4">
                            <div className="w-10 h-10 rounded-xl bg-[#0b141a] flex items-center justify-center shrink-0 mt-0.5">
                                {step.icon}
                            </div>
                            <div className="flex-1">
                                <p className="text-[#e9edef] font-semibold text-sm mb-1">{step.title}</p>
                                <div className="text-sm text-[#8696a0] leading-relaxed">{step.body}</div>
                            </div>
                        </div>
                    ))}
                </div>

                {/* Footer */}
                <div className="px-5 py-4 border-t border-[#2a3942] flex justify-end">
                    <button
                        onClick={onClose}
                        className="px-5 py-2 bg-[#00a884] hover:bg-[#00c49a] text-white text-sm rounded-lg font-medium transition-colors"
                    >
                        Got it
                    </button>
                </div>
            </div>
        </div>
    );
}
