/**
 * build.js - esbuild bundler for wa-chat-summariser
 *
 * Converts the ESM codebase to a single CJS bundle that @yao-pkg/pkg can
 * then wrap alongside Node.js into a standalone Windows executable.
 *
 * Usage:
 *   node build.js
 *
 * Then package:
 *   npx @yao-pkg/pkg dist/entry.cjs --targets node20-win-x64 --output dist/wa-summariser.exe
 */

import { build } from 'esbuild';
import { cpSync, copyFileSync, mkdirSync, existsSync, readFileSync, writeFileSync } from 'fs';
import { resolve, join } from 'path';

const ROOT = resolve('.');
const OUT_DIR = join(ROOT, 'dist');

mkdirSync(OUT_DIR, { recursive: true });

// ── 0. Embed system_prompt.txt as a string constant ─────────────────────────
const promptText = readFileSync(join(ROOT, 'backend', 'system_prompt.txt'), 'utf-8');
const generatedPrompt = `// AUTO-GENERATED by build.js — do not edit manually\nmodule.exports = ${JSON.stringify(promptText)};\n`;
writeFileSync(join(ROOT, 'backend', 'generated-prompt.cjs'), generatedPrompt);
console.log('Embedded system_prompt.txt into generated-prompt.cjs');

// ── 1. esbuild: transpile ESM → CJS, bundle ALL pure-JS deps inline ──────────
// Bundling everything means pkg never needs to resolve packages from its
// virtual snapshot (which can't handle modern "exports" fields in package.json).
// The only things kept external are packages that pkg cannot snapshot anyway
// at build time (e.g. puppeteer downloads Chrome at runtime — that's fine).
console.log('Bundling backend/server.js → dist/bundle.cjs ...');

await build({
    entryPoints: ['backend/server.js'],
    bundle: true,
    platform: 'node',
    target: 'node20',
    format: 'cjs',
    outfile: join(OUT_DIR, 'bundle.cjs'),
    // Keep packages that pass function source-code to Chrome's V8 (page.evaluate)
    // as external so esbuild does NOT transform their code — transformed functions
    // break when serialised to strings for Puppeteer's CDP page.evaluate().
    // Also keep their CJS-with-exports-field deps external (pkg handles them via
    // normal snapshot require).
    // Everything else (axios, groq-sdk, express, socket.io, …) is bundled inline
    // so pkg never needs to resolve modern-exports packages from the snapshot.
    external: [
        'whatsapp-web.js',
        'puppeteer',
        'puppeteer-core',
        '@puppeteer/*',
        'typescript',        // cosmiconfig optional peer dep — not used at runtime
    ],
    // Shim import.meta.url for CJS output so __dirname derivation keeps working
    // both in the bundle and inside the pkg snapshot.
    define: {
        'import.meta.url': '__importMetaUrl',
    },
    banner: {
        js: "const __importMetaUrl = require('url').pathToFileURL(__filename).href;",
    },
    // Suppress expected warnings from whatsapp-web.js dynamic requires
    logLevel: 'warning',
});

console.log('Bundle created.');

// ── 2. Copy static assets into dist/ so pkg snapshots them alongside bundle ──

console.log('Copying system_prompt.txt → dist/system_prompt.txt ...');
copyFileSync(join(ROOT, 'backend', 'system_prompt.txt'), join(OUT_DIR, 'system_prompt.txt'));

const frontendDist = join(ROOT, 'frontend', 'dist');
if (existsSync(frontendDist)) {
    console.log('Copying frontend/dist → dist/frontend/dist ...');
    cpSync(frontendDist, join(OUT_DIR, 'frontend', 'dist'), { recursive: true });
} else {
    console.warn(
        '\nWARNING: frontend/dist not found.\n' +
        'Run  npm run build  first to compile the React frontend.\n'
    );
}

console.log('\nAll done. Next step:\n  npm run package\n');
